### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by TheFractalyst** [PeterCxy/Lolistat#10]
Hey,
I found a lot of bugs and I wish you could solve it.
1-After you open Viber,... when you press back and then you open it again the screen goes dark
2-Text box in a few apps like Tango,... Have problem after you type just one word ( 5-6 alph.).
3-Slow while opening an application.
And so on,
Tested On LG G3 Lollipop

**Comment by PeterCxy** [comment]
@Mo3ein It seems strange that all application starts at a normal speed on my Mi2 with CM12. Can you provide an example of apps that opens slow when Lolistat is activated?

**Comment by TheFractalyst** [comment]
Actually,I'm running stock, This module is usually slow while opening Viber,Go sms,Tango...
The main problem is when the screen goes black when I press back buttom and Textbox show nothing after writing at least one word...

**Comment by BakedTator** [comment]
Having the same black screen bug with the XDA premium app...if I mo e the screen up and down it sometimes comes back for a minute then goes black again...jflteusc on vanir 5.0.2
