### ISSUE TITLE
Bug with BBM app

### ISSUE THREAD

**Issue by f3yisayo** [PeterCxy/Lolistat#13]
The status bar tints fine, but bbm's menu at the bottom loses its margin making the nav bar cover the menu a bit, and when you try to send/reply a message, the keyboard covers the field to input text. I'll try to come up with logs.

![screenshot_2015-02-27-10-52-29](https://cloud.githubusercontent.com/assets/9140532/6410381/36b5a3fc-be6f-11e4-8acf-5052f0944726.png)
![screenshot_2015-02-27-10-53-01](https://cloud.githubusercontent.com/assets/9140532/6410382/36ba22ec-be6f-11e4-9fee-3dec7d5dca9a.png)
![screenshot_2015-02-27-10-53-11](https://cloud.githubusercontent.com/assets/9140532/6410383/36bd2a3c-be6f-11e4-989f-f1f3de17ce99.png)

**Comment by PeterCxy** [comment]
see the closed issues list. This was fixed yesterday. The fix will be included in the next release.

**Comment by f3yisayo** [comment]
Oh okay, awesome, can't wait. Also, do you have any plans of adding support for apps that should be blacklisted from using the module?

**Comment by PeterCxy** [comment]
Yes I have the plan, but it is still too early to add a blacklist, because I think I can do better in auto-detecting.
