### ISSUE TITLE
Color incorrect in apps that auto-collapse the toolbar

### ISSUE THREAD

**Issue by Ma7moodHD** [PeterCxy/Lolistat#15]
When i scroll down the top bar become hidden then the status bar and navigation bar color changed to white.

If i scroll up the top bar become visible then the status bar and n

**Comment by Ma7moodHD** [comment]
and navigation bar color changed to blue. Can you find w way to make the status bar translucent when we scroll down ?

**Comment by PeterCxy** [comment]
So it is in the new XDA One app. I am thinking of a way to detect this motion but I can't guarantee that it would be perfect.

**Comment by PeterCxy** [comment]
fixed for some apps with ActionBar, but it is not possible to fix it for all apps
