### ISSUE TITLE
Make features customizable

### ISSUE THREAD

**Issue by JasprW** [PeterCxy/Lolistat#16]
Many people like me doesn't like the navigation bar been tinted.

**Comment by merrickluo** [comment]
cant agree more

**Comment by Bokoblin** [comment]
Same thing, create a per-app black list because it unactive immersive nav bar on games and affect Google Play Games integration too in game. I must inactive it until a new version with the blacklist

**Comment by PeterCxy** [comment]
This is in plan, all features will be customizable, but not in 1.0.x releases.
