### ISSUE TITLE
Line 58 in ModLoli.java

### ISSUE THREAD

**Issue by f3yisayo** [PeterCxy/Lolistat#17]
After facing a lot of issues with importing the project into Android studio, I finally got things to be fine without errors,  now I'm not sure what's going on and how it builds fine for you but when I try to build the project. 

Line 58 of `ModLoli.java` returns an incompatible types error. 

`final int theme_translucentStatus = internalTranslucentStatusField.get(null);`

When I change `.get` to `.getInt(null)`. The error disappears.

**Comment by PeterCxy** [comment]
That's an error caused by my compiler. Thank you. I'll fix this.

**Comment by f3yisayo** [comment]
Surprisingly, when I changed that line to getInt(null) and built the project, the status bar no longer tints in apps anymore.
