### ISSUE TITLE
You definitely need to add a UI of sorts

### ISSUE THREAD

**Issue by ghost** [PeterCxy/Lolistat#19]
This is a really great module, however it's lack customizability comes at the expense of functionality in some apps. You need to add the option to disable StatBar/NavBar, or at least the NavBar, after all the name suggests this is only a StatBar modifier, and some people may not like NavBar tint. Also per-app enabling is a must for a future release, for example on reddit news it nearly breaks all functionality. 
(

**Comment by ghost** [comment]
(http://imgur.com/a/hGCxJ)

**Comment by PeterCxy** [comment]
duplicate
