### ISSUE TITLE
Possible suggestion to fix apps like Snapchat and Instagram

### ISSUE THREAD

**Issue by HiFIi** [PeterCxy/Lolistat#20]
Hello!

I have thought of a possible solution to fix some apps that have been reported not working/apps that are being difficult. But I'm not quite sure if would be the best way, haha.

You could maybe try using a packageUrl (Url) and create some sort of if-else statement, like... if packagename = com.snapchat.android, then set the statusbarColor/navigationbarColor depending on what the user has chosen in your settingsactivity, amongst the other stuff.

I know that's a pretty lazy description of my potential workaround, but you're a smart guy and I know you can figure it out. If this is a stupid idea, then my apologies.

Anyways, I can't thank you enough for what you have created, and look forward to future updates.

**Comment by PeterCxy** [comment]
I don't think it is the correct way to do this. If the module cannot auto-detect, then I would not have published it.
