### ISSUE TITLE
Lolistat App Notification Issues

### ISSUE THREAD

**Issue by roguereaper7** [PeterCxy/Lolistat#21]
Hello,

Great module and I enjoyed using it, but what I've noticed is that app notifications are reduced to a white silhouette, which may end up confusing to most because of the similar shapes of the icons with other app icons. Is it possible to retain the app notifications color, text, etc?

**Comment by PeterCxy** [comment]
Sorry but it is not possible. I will add an option for coloring the icons in the future.
