### ISSUE TITLE
HTC One System Ui Force Close sometimes on Recent apps

### ISSUE THREAD

**Issue by MDXDave** [PeterCxy/Lolistat#22]
System UI Force Close sometimes on Recent apps view

**Comment by MDXDave** [comment]
HTC One with Android 5.0.2 / Sense 6.0

**Comment by HiFIi** [comment]
Best to accompany a log alongside something like this imo.

**Comment by MDXDave** [comment]
Has something to do with HTC Keyguard

> V/SystemUIService(25707): start class com.android.systemui.volume.VolumeUI in 91
> D/SystemUIService(25707): loading: class com.android.systemui.statusbar.SystemBars
> D/SystemUIService(25707): running: com.android.systemui.statusbar.SystemBars@3463b824
> D/SystemBars(25707): start
> V/SystemUIService(25707): start class com.android.systemui.statusbar.SystemBars in 5
> D/SystemUIService(25707): loading: class com.android.systemui.usb.StorageNotification
> D/SystemUIService(25707): running: com.android.systemui.usb.StorageNotification@1c504542
> V/SystemUIService(25707): start class com.android.systemui.usb.StorageNotification in 3
> D/SystemUIService(25707): loading: class com.android.systemui.power.PowerUI
> D/SystemUIService(25707): running: com.android.systemui.power.PowerUI@1653c953
> V/SystemUIService(25707): start class com.android.systemui.power.PowerUI in 15
> D/SystemUIService(25707): loading: class com.android.systemui.media.RingtonePlayer
> D/SystemUIService(25707): running: com.android.systemui.media.RingtonePlayer@3e73e7bc
> V/SystemUIService(25707): start class com.android.systemui.media.RingtonePlayer in 3
> D/SystemUIService(25707): loading: class com.android.systemui.screenshot.ScreenshotService
> D/SystemUIService(25707): running: com.android.systemui.screenshot.ScreenshotService@1f5d2345
> I/IntentController(25707): initialize receiver background thread:3
> I/IntentController(25707): initialize intent controller first time!
> I/IntentController(25707): register(screenshot,com.htc.action.SCREEN_CAPTURE_BG,true):create
> I/ScreenshotService(25707): startScreenshotService:7
> V/SystemUIService(25707): start class com.android.systemui.screenshot.ScreenshotService in 8
> V/KeyguardServiceDelegate( 1219): **\* Keyguard connected (yay!)
> D/StatusBarManagerService( 1219): manageDisableList userId=0 what=0x3200000 pcg=com.android.systemui
> D/PMS     ( 1219): acquireWL(10cb5a29): PARTIAL_WAKE_LOCK  show keyguard 0x1 25707 10006 null
> I/HtcDLNAMiddlelayer(10826): Play Position: unknown, Renderer:[ V [ G 3 L 6 0 - T ] L ] 2 A 2 8 Z 
> D/HtcDLNAMiddlelayer(10826): [positionQueryTask] Get position -1
> D/SystemBars.ServiceMonitor(25707): startService mServiceName=null
> D/SystemBars(25707): onNoService
> D/SystemBars(25707): createStatusBarFromConfig
> D/StatusBar(25707): has navigation bar = false
> I/StatusBar(25707): reminderEnabled:false
> I/StatusBarManagerService( 1219): registerStatusBar bar=com.android.internal.statusbar.IStatusBar$Stub$Proxy@3fabb69d
> D/HtcKeyguardStatusView(25707): onFinishInflate
> D/HtcKeyguardStatusView(25707): HtcLockScreen exist
> D/Ray     (25707): getKeyguardMastHeadView_HTC
> D/HtcKeyguardUtils(25707): other exception - null
> D/HtcKeyguardUtils(25707): java.lang.reflect.InvocationTargetException
> D/HtcKeyguardUtils(25707):     at java.lang.reflect.Method.invoke(Native Method)
> D/HtcKeyguardUtils(25707):     at java.lang.reflect.Method.invoke(Method.java:372)
> D/HtcKeyguardUtils(25707):     at com.android.keyguard.htc.HtcKeyguardUtils.getKeyguardMastHeadView_HTC(HtcKeyguardUtils.java:158)
> D/HtcKeyguardUtils(25707):     at com.android.keyguard.htc.HtcKeyguardStatusView.onFinishInflate(HtcKeyguardStatusView.java:43)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.rInflate(LayoutInflater.java)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.parseInclude(LayoutInflater.java)
> D/HtcKeyguardUtils(25707):     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
> D/HtcKeyguardUtils(25707):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.parseInclude(Unknown Source)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.rInflate(LayoutInflater.java)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.parseInclude(LayoutInflater.java)
> D/HtcKeyguardUtils(25707):     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
> D/HtcKeyguardUtils(25707):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.parseInclude(Unknown Source)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.rInflate(LayoutInflater.java)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.rInflate(LayoutInflater.java)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.inflate(LayoutInflater.java)
> D/HtcKeyguardUtils(25707):     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
> D/HtcKeyguardUtils(25707):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.inflate(Unknown Source)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.inflate(LayoutInflater.java)
> D/HtcKeyguardUtils(25707):     at android.view.LayoutInflater.inflate(LayoutInflater.java)
> D/HtcKeyguardUtils(25707):     at android.view.View.inflate(View.java)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:674)
> D/HtcKeyguardUtils(25707):     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
> D/HtcKeyguardUtils(25707):     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(Unknown Source)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:3141)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:3137)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:578)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:619)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
> D/HtcKeyguardUtils(25707):     at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
> D/HtcKeyguardUtils(25707):     at android.os.Handler.dispatchMessage(Handler.java)
> D/HtcKeyguardUtils(25707):     at android.os.Looper.loop(Looper.java)
> D/HtcKeyguardUtils(25707):     at android.app.ActivityThread.main(ActivityThread.java)
> D/HtcKeyguardUtils(25707):     at java.lang.reflect.Method.invoke(Native Method)
> D/HtcKeyguardUtils(25707):     at java.lang.reflect.Method.invoke(Method.java:372)
> D/HtcKeyguardUtils(25707):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
> D/HtcKeyguardUtils(25707):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
> D/HtcKeyguardUtils(25707):     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
> D/HtcKeyguardUtils(25707): Caused by: java.lang.ClassCastException: com.android.keyguard.htc.HtcKeyguardStatusView cannot be cast to com.htc.lockscreen.ui.EmptyKeyguardStatusView
> D/HtcKeyguardUtils(25707):     at com.htc.lockscreen.ui.MasterHeadView.createView(Unknown Source)
> D/HtcKeyguardUtils(25707):     ... 44 more

**Comment by HiFIi** [comment]
And to make it less work to scroll to the bottom each time, I'd also recommend (next time) that you maybe post the log to a site like pastebin, and then paste the link to the log instead. Less messy. :)

We don't know if PeterCxy has an HTC phone lying around, which would make it hard to find the problem(s), so that's why a log is important in this case

**Comment by MDXDave** [comment]
Okay, I think its not a lolistat-releated problem. I got OutOfMemoryExceptions everytime, caused by com.android.systemui.recent.htc.RecentAppTaskLoader...
