### ISSUE TITLE
Whatsapp and Snapchat bugs

### ISSUE THREAD

**Issue by danielmizrachi** [PeterCxy/Lolistat#34]
Hiya,

So I've been using this moldule for about an hour so far and I love what it does. But I already have two bug reports to file.
1) When dimissing the status bar and caption when viewing a Whatsapp image a contact has sent you (by simply tapping the screen), the status bar is replaced by the action bar from the previous screen. I can't imagine why this would be the case.
2) When entering a Snapchat text chat, the status bar goes white meaning no icons can be seen. I know this is just the module adapting but it's a clear bug and I don't want to blacklist Snapchat in the settings just due to this. Furthermore, I think the status bar should turn the green action bar colour when on the app's main screen rather than black.
Screenshots:

![screenshot_2015-04-19-10-03-19](https://cloud.githubusercontent.com/assets/5166310/7218888/7fa6902c-e67d-11e4-8889-6e0eaa946bd3.png)
![screenshot_2015-04-19-09-39-25](https://cloud.githubusercontent.com/assets/5166310/7218889/7fa86442-e67d-11e4-9032-b6a9f78a5508.png)

Thanks in advance,
Daniel

**Comment by PeterCxy** [comment]
Apps may have extremely different implementations of their styles, so it is really hard to adapt to all of them. These days I have no time to work on this module, and sorry for the long break of the module's maintaince. I will try to fix these bugs as soon as I have some spare time.

**Comment by danielmizrachi** [comment]
Okay, I just wanted to contribute in case you could do something. No worries.
