### ISSUE TITLE
Some bugs in htc One M8

### ISSUE THREAD

**Issue by Ma7moodHD** [PeterCxy/Lolistat#7]
Hello

in the BBM app the buttons bar is now located behind the navigation bar.

Also the recent apps is not visible. I'm using Android stock recent apps style.

htc One M8
Android 5.0.1
Sense 6

Sorry for my english

**Comment by PeterCxy** [comment]
I'll take a look into the BBM bug, but I cannot figure out what's wrong with the recent apps because I have no HTC device.
